version: "3.9"
services:
  api:     
    build: .
    image: uricbonatti/weather-playlists-api:v1
    container_name: weather-playlists-api
    ports: 
      - "3333:3333"
    networks:
      - challenge
    environment:
      OPEN_WEATHER_API_KEY: b77e07f479efe92156376a8b07640ced
      SPOTIFY_CLIENT_ID: 4d8f63b3e1894c73a9d6fa0e7085e60f
      SPOTIFY_SECRET: 6dd251a17f9a422b9ba04175438ad8ab
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      REDIS_PASS: 
      MAX_REQUESTS: 10
      MINUTES_RESEND_REQUEST: 5
      PORT:
     
    depends_on:
      - "redis"
  
  redis:
    image: redis:alpine
    container_name: weather-playlists-redis
    networks: 
      - challenge

networks:
  challenge:
    driver: bridge
