openapi: 3.0.1
info:
  title: Weather Soundtrack API
  description: API para obtenção de uma playlist de acordo com a temperatuda de um
    local/cidade
  contact:
    email: uricbonatti.eng@gmail.com
  version: 1.0.0
servers:
- url: https://localhost:3333/
- url: http://localhost:3333/
paths:
  /tracks:
    get:
      tags:
      - Weather Soundtrack
      summary: Retorna uma playlist de acordo com a temperatura
      description: Realiza a busca por cidade ou coordenada e retorna uma playlist
        do spotify adequada para a temperatura do local
      operationId: tracks
      parameters:
      - name: city
        in: query
        description: Nome da cidade que se quer obter a playlist
        schema:
          $ref: '#/components/schemas/City'
      - name: lat
        in: query
        description: Latitude do local
        schema:
          $ref: '#/components/schemas/Latitude'
      - name: lon
        in: query
        description: Longitude do local
        schema:
          $ref: '#/components/schemas/Longitude'
      responses:
        200:
          description: Playlist obtida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Soundtrack'
        400:
          description: Entrada Invalida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        429:
          description: Erro de excesso de requisições por IP
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LimitAccessError'
        500:
          description: Erro interno do Servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
components:
  schemas:
    City:
      type: string
      example: São Paulo
    Latitude:
      type: number
      example: -23.5
    Longitude:
      type: number
      example: -46.5
    InternalError:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: Internal Server Error
    ValidationError:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: city or valid coordinates(lon,lon) must be informed.
        route:
          type: string
          example: /tracks
        examples:
          type: string
          example: /tracks?city=São Paulo /tracks?lat=-23.5&lon=-46.6
    LimitAccessError:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: Too many requests from this IP, please try again after 5 minutes
    Soundtrack:
      type: object
      properties:
        tracks:
          type: object
          properties:
            href:
              type: string
              example: https://api.spotify.com/v1/search?query=genre%3Apop+music&type=track&offset=0&limit=20
            items:
              minItems: 0
              type: array
              items:
                type: object
                properties:
                  album:
                    type: object
                    properties: {}
                  artists:
                    minItems: 1
                    type: array
                    items:
                      type: object
                      properties: {}
                  disc_number:
                    type: number
                    example: 1.0
                  duration_ms:
                    type: number
                    example: 235766.0
                  explicit:
                    type: boolean
                    example: false
                  external_ids:
                    type: object
                    properties: {}
                  href:
                    type: string
                    example: https://api.spotify.com/v1/tracks/5JixKG2cp8uTu7RmjmD0aQ
                  external_urls:
                    type: object
                    properties:
                      spotify:
                        type: string
                        example: https://open.spotify.com/track/5JixKG2cp8uTu7RmjmD0aQ
                  id:
                    type: string
                    example: 5JixKG2cp8uTu7RmjmD0aQ
                  is_local:
                    type: boolean
                    example: false
                  name:
                    type: string
                    example: Love Story (Taylor’s Version)
                  popularity:
                    type: number
                    example: 0.0
                  type:
                    type: string
                    example: track
                  uri:
                    type: string
                    example: spotify:track:5JixKG2cp8uTu7RmjmD0aQ
            limit:
              type: number
              example: 1.0
            next:
              type: string
              example: https://api.spotify.com/v1/search?query=genre%3Apop+music&type=track&offset=20&limit=20
            offset:
              type: number
              example: 0.0
            previous:
              type: string
              example: null
            total:
              type: string
              example: "10000"
